create table "public"."departments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "slug" text not null
);


alter table "public"."departments" enable row level security;

create table "public"."executives" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid default gen_random_uuid(),
    "department" text
);


alter table "public"."executives" enable row level security;

create table "public"."managers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid default gen_random_uuid(),
    "department" text
);


alter table "public"."managers" enable row level security;

CREATE UNIQUE INDEX departments_pkey ON public.departments USING btree (id);

CREATE UNIQUE INDEX departments_slug_key ON public.departments USING btree (slug);

CREATE UNIQUE INDEX executives_pkey ON public.executives USING btree (id);

CREATE UNIQUE INDEX managers_pkey ON public.managers USING btree (id);

alter table "public"."departments" add constraint "departments_pkey" PRIMARY KEY using index "departments_pkey";

alter table "public"."executives" add constraint "executives_pkey" PRIMARY KEY using index "executives_pkey";

alter table "public"."managers" add constraint "managers_pkey" PRIMARY KEY using index "managers_pkey";

alter table "public"."departments" add constraint "departments_slug_key" UNIQUE using index "departments_slug_key";

alter table "public"."executives" add constraint "executives_department_fkey" FOREIGN KEY (department) REFERENCES departments(slug) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."executives" validate constraint "executives_department_fkey";

alter table "public"."executives" add constraint "executives_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."executives" validate constraint "executives_user_id_fkey";

alter table "public"."managers" add constraint "managers_department_fkey" FOREIGN KEY (department) REFERENCES departments(slug) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."managers" validate constraint "managers_department_fkey";

alter table "public"."managers" add constraint "managers_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."managers" validate constraint "managers_user_id_fkey";

grant delete on table "public"."departments" to "anon";

grant insert on table "public"."departments" to "anon";

grant references on table "public"."departments" to "anon";

grant select on table "public"."departments" to "anon";

grant trigger on table "public"."departments" to "anon";

grant truncate on table "public"."departments" to "anon";

grant update on table "public"."departments" to "anon";

grant delete on table "public"."departments" to "authenticated";

grant insert on table "public"."departments" to "authenticated";

grant references on table "public"."departments" to "authenticated";

grant select on table "public"."departments" to "authenticated";

grant trigger on table "public"."departments" to "authenticated";

grant truncate on table "public"."departments" to "authenticated";

grant update on table "public"."departments" to "authenticated";

grant delete on table "public"."departments" to "service_role";

grant insert on table "public"."departments" to "service_role";

grant references on table "public"."departments" to "service_role";

grant select on table "public"."departments" to "service_role";

grant trigger on table "public"."departments" to "service_role";

grant truncate on table "public"."departments" to "service_role";

grant update on table "public"."departments" to "service_role";

grant delete on table "public"."executives" to "anon";

grant insert on table "public"."executives" to "anon";

grant references on table "public"."executives" to "anon";

grant select on table "public"."executives" to "anon";

grant trigger on table "public"."executives" to "anon";

grant truncate on table "public"."executives" to "anon";

grant update on table "public"."executives" to "anon";

grant delete on table "public"."executives" to "authenticated";

grant insert on table "public"."executives" to "authenticated";

grant references on table "public"."executives" to "authenticated";

grant select on table "public"."executives" to "authenticated";

grant trigger on table "public"."executives" to "authenticated";

grant truncate on table "public"."executives" to "authenticated";

grant update on table "public"."executives" to "authenticated";

grant delete on table "public"."executives" to "service_role";

grant insert on table "public"."executives" to "service_role";

grant references on table "public"."executives" to "service_role";

grant select on table "public"."executives" to "service_role";

grant trigger on table "public"."executives" to "service_role";

grant truncate on table "public"."executives" to "service_role";

grant update on table "public"."executives" to "service_role";

grant delete on table "public"."managers" to "anon";

grant insert on table "public"."managers" to "anon";

grant references on table "public"."managers" to "anon";

grant select on table "public"."managers" to "anon";

grant trigger on table "public"."managers" to "anon";

grant truncate on table "public"."managers" to "anon";

grant update on table "public"."managers" to "anon";

grant delete on table "public"."managers" to "authenticated";

grant insert on table "public"."managers" to "authenticated";

grant references on table "public"."managers" to "authenticated";

grant select on table "public"."managers" to "authenticated";

grant trigger on table "public"."managers" to "authenticated";

grant truncate on table "public"."managers" to "authenticated";

grant update on table "public"."managers" to "authenticated";

grant delete on table "public"."managers" to "service_role";

grant insert on table "public"."managers" to "service_role";

grant references on table "public"."managers" to "service_role";

grant select on table "public"."managers" to "service_role";

grant trigger on table "public"."managers" to "service_role";

grant truncate on table "public"."managers" to "service_role";

grant update on table "public"."managers" to "service_role";


